blank_issues_enabled: false
contact_links:
  - name: A2ABench Feedback Form
    url: https://a2abench-api.web.app/feedback
    about: Use this for general feedback. GitHub issues are reserved for reproducible bugs and feature requests.
